import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Book Store",
  description: "Generated by My Book Store",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <footer>This is a footer</footer>
      </body>
    </html>
  );
}
